#pragma once

#define SLANG_RHI_ENABLE_CPU 1
#define SLANG_RHI_ENABLE_D3D11 1
#define SLANG_RHI_ENABLE_D3D12 1
#define SLANG_RHI_ENABLE_VULKAN 1
#define SLANG_RHI_ENABLE_METAL 1
#define SLANG_RHI_ENABLE_CUDA 1
#define SLANG_RHI_ENABLE_WGPU 1
#define SLANG_RHI_ENABLE_AGILITY_SDK 1
#define SLANG_RHI_ENABLE_NVAPI 1
#define SLANG_RHI_ENABLE_OPTIX 1
#define SLANG_RHI_BUILD_SHARED 1
