using static SlangNet.Unsafe.SlangPassThrough;

namespace SlangNet;

public enum PassThrough
{
    None = SLANG_PASS_THROUGH_NONE,
    FXC = SLANG_PASS_THROUGH_FXC,
    DXC = SLANG_PASS_THROUGH_DXC,
    GLSLang = SLANG_PASS_THROUGH_GLSLANG,
    SPIRVDis = SLANG_PASS_THROUGH_SPIRV_DIS,
    Clang = SLANG_PASS_THROUGH_CLANG,
    VisualStudio = SLANG_PASS_THROUGH_VISUAL_STUDIO,
    Gcc = SLANG_PASS_THROUGH_GCC,
    GenericCCpp = SLANG_PASS_THROUGH_GENERIC_C_CPP,
    NVRTC = SLANG_PASS_THROUGH_NVRTC,
    LLVM = SLANG_PASS_THROUGH_LLVM,
    SPIRVOpt = SLANG_PASS_THROUGH_SPIRV_OPT,
}
